- name: Bootstraps this ansible collection itself
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_user: "{{ lookup('env', 'USER') }}"
    github_username: korbad
  tasks:
  - name: Ensure authorized_keys for GitHub user {{ github_username }} is present for local user {{ ansible_user }}
    ansible.posix.authorized_key:
      user: "{{ ansible_user }}"
      key: "https://github.com/{{ github_username }}.keys"
      manage_dir: true
